version: '2'
services:

  webserver:
    build:
      context: .
      dockerfile: Dockerfile

    working_dir: /usr/src/app
    command: ./docker/cmd-webserver.sh
    ports: ["8011:8011"]
    env_file: ./docker/.env
    restart: "always"
